### ISSUE TITLE
How to get the configuration for fisheye images? 

### ISSUE THREAD

**Issue by adityapuranik99** [jianwang-mpi/egowholemocap#4]
I see your fisheye_calibration json and I was wondering if there is a way that you figure that out for any other fisheye image. 

This is a great contribution, love it thanks.

**Comment by jianwang-mpi** [comment]
I got the fisheye parameters by using the OCamCalib: https://sites.google.com/site/scarabotix/ocamcalib-omnidirectional-camera-calibration-toolbox-for-matlab

Please note that the Matlab version requirement: "The OCamCalib Toolbox for Matlab has been successfully tested under Matlab 8.0, 8.1 2013 for Windows, MacOS and Linux."
