### ISSUE TITLE
EgoPW dataset

### ISSUE THREAD

**Issue by naso06** [jianwang-mpi/egowholemocap#5]
Hello,

Your research has left a strong impression on me.

In your paper, you mentioned, "we use our EgoWholeBody dataset and the EgoPW dataset [48]."

But there is only fine-tune the model using the SceneEgo dataset.

I would like to know if the EgoPW dataset and the SceneEgo dataset are the same.

Additionally, I would like to learn how to fine-tune the model using the EgoPW dataset.

Thank you.

**Comment by naso06** [comment]
Also, you mentioned "The network is trained on the combination dataset of EgoWholeBody and EgoPW. The ratio between
the EgoWholeBody and EgoPW datasets is 9:1". 

I would like to know how can I train the model with mix dataset(EgowholeBody and EgoPW 9:1)

**Comment by jianwang-mpi** [comment]
Hello,

The EgoPW dataset and SceneEgo dataset are not the same. 

Through my further experiments, I found that if you do not use the EgoPW dataset, the training results remain the same. So it is not necessary to train with the EgoPW dataset anymore.

**Comment by naso06** [comment]
Thank you for your quick reply.

**Comment by naso06** [comment]
I would like to know how to evaluate the model with GlobalEgo dataset and Mo2Cap2 dataset.

**Comment by jianwang-mpi** [comment]
Hello,

I do not have time to release the test code for GlobalEgoMocap and Mo2Cap2 datasets. You can have a look into:

mmpose/datasets/datasets/egocentric/global_ego_test_dataset.py
mmpose/datasets/datasets/egocentric/mo2cap2_test_dataset.py

These files show you how to load the dataset.

If you know how to use MMPose, you can test it on your own test dataset easily.

**Comment by naso06** [comment]
Thank you for your reply.

I have been carefully following the provided code to reproduce the quantitative results mentioned in your paper.

However, I have observed a discrepancy between the results reported in the paper and the outcomes I obtained using the provided code.

For GlobalEgoMocap test dataset, 
PA-MPJPE
paper(single): 68.59
outcome: 85.12

BA-MPJPE
paper(single):55.92
outcome: 72.90


For Mo2Cap2 test dataset, 
PA-MPJPE
paper(single): 74.66
outcome: 129.21

BA-MPJPE
paper(single): 59.26
outcome: 112.54

I have double-checked my setup and ensured that all steps were followed as outlined in the instructions. Despite this, the performance gap persists, leading me to wonder if there might be some details or potential issues that I may have overlooked.

Could you please provide any insights or suggestions on what might be causing this difference? I would greatly appreciate your guidance to better understand and resolve this issue.

Thank you very much for your time and assistance.

**Comment by jianwang-mpi** [comment]
Hello,

For the GlobalEgoMocap test dataset, you need to add the EgoPW dataset in training and fine-tune it with the EgoPW dataset.

I am sorry for misleading you about the use of the EgoPW dataset. It makes a difference for the GlobalEgoMocap dataset.

Download the Egopw dataset from https://vcai.mpi-inf.mpg.de/projects/egopw/

See mmpose/datasets/datasets/egocentric/egopw_finetune_dataset.py for loading the dataset.

For the Mo2Cap2 results, I have no idea about the very large discrepancy.

**Comment by naso06** [comment]
Thank you very much for your reply!

**Comment by naso06** [comment]
I would like to know how to train to test on GlobalEgoMocap and Mo2Cap2 test dataset.

I tried to train and finetuning with EgoPW dataset but I couldn't get the same result in your paper..

My result
pa-mpjpe
GlobalEgoMocap: 71.78
Mo2Cap2: 80.90

**Comment by naso06** [comment]
Thank you!
