### ISSUE TITLE
SceneEgo hand annotation

### ISSUE THREAD

**Issue by naso06** [jianwang-mpi/egowholemocap#8]
Hello,

I would like to inquire whether it is appropriate to use the SceneEgo test dataset hand annotation for fine-tuning the hand pose estimation module. Additionally, if the SceneEgo train dataset hand annotation is available, could you kindly provide it?

Thank you very much for your time, and I look forward to your valuable response.

Best regards,

**Comment by jianwang-mpi** [comment]
Hello,

I have updated the training dataset hand annotations.

https://nextcloud.mpi-klsb.mpg.de/index.php/s/5ZjtY928LPj9ERz

Please check.

**Comment by naso06** [comment]
Thank you!
